# Generated by Django 5.2.11 on 2026-03-10 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("audit_date", models.DateTimeField(auto_now_add=True)),
                (
                    "evaluated_programme",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "evaluated_major",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("can_graduate", models.BooleanField(default=False)),
                ("total_credits_earned", models.FloatField(default=0.0)),
                ("total_credits_required", models.FloatField(default=0.0)),
                (
                    "overall_progress",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("unmet_requirements_json", models.JSONField(default=list)),
                ("next_steps_json", models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name="StudentProfile",
            fields=[
                (
                    "student_number",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=255)),
                ("programme", models.CharField(blank=True, default="", max_length=255)),
                ("major", models.CharField(blank=True, default="", max_length=255)),
                ("overall_gpa", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="BucketResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("component_name", models.CharField(default="General", max_length=255)),
                ("bucket_name", models.CharField(max_length=255)),
                ("is_met", models.BooleanField(default=False)),
                ("credits_earned", models.FloatField(default=0.0)),
                ("credits_required", models.FloatField(default=0.0)),
                ("is_all_required", models.BooleanField(default=False)),
                ("courses_completed_json", models.JSONField(default=list)),
                ("courses_needed_json", models.JSONField(default=list)),
                (
                    "audit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bucket_results",
                        to="performance.auditrecord",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="auditrecord",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="audits",
                to="performance.studentprofile",
            ),
        ),
    ]
