# Generated by Django 5.2.11 on 2026-03-31 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='flr_exempt_verified',
            field=models.BooleanField(default=False),
        ),
    ]
