# Generated by Django 5.2.11 on 2026-03-24 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("performance", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditrecord",
            name="total_credits_earned",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="auditrecord",
            name="total_credits_required",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="bucketresult",
            name="credits_earned",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="bucketresult",
            name="credits_required",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
