# Generated by Django 5.2.11 on 2026-03-25 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("performance", "0002_alter_auditrecord_total_credits_earned_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditrecord",
            name="total_credits_earned",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="auditrecord",
            name="total_credits_required",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="bucketresult",
            name="credits_earned",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="bucketresult",
            name="credits_required",
            field=models.FloatField(default=0.0),
        ),
    ]
