# Generated by Django 5.2.11 on 2026-04-06 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("performance", "0002_studentprofile_flr_exempt_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="bucketresult",
            name="exemption_mappings_json",
            field=models.JSONField(default=list),
        ),
    ]
