# Generated by Django 5.2.11 on 2026-04-06 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("performance", "0003_bucketresult_exemption_mappings_json"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="raw_transcript_text",
            field=models.TextField(blank=True, default=""),
        ),
    ]
