# Generated by Django 5.2.11 on 2026-04-06 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("performance", "0003_alter_auditrecord_total_credits_earned_and_more"),
        ("performance", "0004_studentprofile_raw_transcript_text"),
    ]

    operations = []
