# Generated by Django 5.2.11 on 2026-04-07 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("performance", "0005_merge_20260406_1900"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentprofile",
            name="raw_transcript_text",
        ),
    ]
