# Generated by Django 5.2.11 on 2026-04-08 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0006_remove_studentprofile_raw_transcript_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditrecord',
            name='evaluated_minor',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='minor',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
