# Generated by Django 5.2.11 on 2026-04-08 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0007_add_minor_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='bucketresult',
            name='component_type',
            field=models.CharField(default='Major', max_length=50),
        ),
    ]
