# Generated by Django 5.2.11 on 2026-04-07 06:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Faculty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("code", models.CharField(max_length=10, unique=True)),
            ],
            options={
                "verbose_name_plural": "Faculties",
            },
        ),
        migrations.AddField(
            model_name="customuser",
            name="approved_at",
            field=models.DateTimeField(
                blank=True, help_text="When this account was activated.", null=True
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                help_text="The administrator who activated this account.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_accounts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="faculties",
            field=models.ManyToManyField(
                blank=True,
                help_text="Select the faculties this advisor is authorized to view.",
                related_name="advisors",
                to="accounts.faculty",
            ),
        ),
    ]
